language: ruby
rvm:
- 2.6
install:
  - gem install jekyll -v 3.8.5
  - gem install jekyll-text-theme -v 1.5.0
script:
  - jekyll build
deploy:
  provider: s3
  bucket: szakallas.eu
  access_key_id:
    secure: U8l0btCMXTqxz3MuqnCwZwL+f/nXP0AJ/Aq7W02ZkrWhpNR2+gkcljBw/TVImccJFyPQVDDC1OHl6HBj5f56Kd4IvAX3fFVwC4g0CjAvc4GBfFx2eKUQN3IzeO0oZZfkMP4iSUU7yexT4OIoNZ1Ucc7LXklO8J6Q5NkieOeuGPUrle3+Q+7ZzQdWEF1k4LPztV/B/1kRXaBKwd+vFiYgfS3khd0qUzjtZxEOtiKYE80Jj6JhxQJ5susGrKwu4PE89LVdLuGLErRghNbkfzqA+FOgZfinHJqGyTKwzGLRYJuNWkulGRFwNr45Yf38sYjXCaVhnDjnhzmpxc+oN3A92PQo5U0UrAUFhnk36KU5XM3aXJYZf/V03os4+17S1imgAuGrJ3XzXz82DiKQ1yoZOo0bvB5OjByn3knw+0iTxNkWc77Wvjo1rV03r0uRC4ePTaQ1GosetqBaccvNe+9i6BsEz1V6UJFC5W3JO3nFQcI4B6qg+kRps60Hd4UWPLjOryoKzZ8UqupjvLjBA9XzdBLVKLDsCN4mIh2oFFTyJhpPHqmYUTySlBARwmnjYZYJMaw3TFVHnD4mnGjSqkaZTc9jh0tp3ROcgkPFoowyqSYd0d0uG4ASrnBz7gPZeUHXc97v3tXTa6D2Tnvt1m8EpGdqCWV34oB7vfVM4bUrbTE=
  secret_access_key:
    secure: gy4YM2uL/51HKjnV16I3KiTecYoM70Tjd6Sw5hSOQtl7l1S1IF+21RHB0+WX27qhwRMttFuPfmovK9fKzg9FIkn6kHAjQa9mGzjMIvBxI45sTSSQL36lWbvfpW2tMbWVNG++1Tm7hF2BePjMnV3iO59+PGJ5Sh5V/oAspjYBq0wqTGm5wJvaMRJFB/etnd8r39Of60Z6FlpW0EraCPDTycqkTR1mAbLSWTtsN4mbDR/BkFzzTNtlk8Wv9saZCJ5PdMLAhilgI43vBLZEezYUpg/ayYRPPiz1pJZ57KIYsjTxf08M/YwIcepGcK0o/r5R6fLV9TTsZQs+UmJAt1V8y5kVqg6h8u69dKer3Queet2WEwed1pi+FGDYdeUCxwM2eIw2XDTwY9tGRGDdKHMPQRAYQZ/9H3EkUqfI6e/iBUhV40tY5iyszv44hkiO3hEafc9t9MceIANplcJEjRWCzXa7dWmgqIL/RQEMx+IQJqk0MTyVm8EdZ/CKJEalK3WeRxc/xjxLl2JVNSO7As+1WuF8mkrAzljhO/7cLyRmjuLZ7gGkfcWOF93fOjoqekK5Wz6uygggWgJKLbD2halxkhm6mxHacm2QujfSCkPLhG77pUvraQYobMgbBjqz401++ujCb/hFIIljojJAjOkv4YpJsDVcV1xjvWG4slx7ngA=
  local_dir: _site
  skip_cleanup: true
